export const EQUIPMENT = [
  { id: 1, name: "Barbell" },
  { id: 2, name: "Body weight" },
  { id: 3, name: "Cable" },
  { id: 4, name: "Dumbbell" },
  { id: 5, name: "EZ Barbell" },
  { id: 6, name: "Leverage machine" },
  { id: 7, name: "Sled machine" },
  { id: 8, name: "Smith machine" },
  { id: 9, name: "Weighted" },
  { id: 10, name: "Assisted" },
  { id: 11, name: "Band" },
  { id: 12, name: "Battling Rope" },
  { id: 13, name: "Bosu ball" },
  { id: 14, name: "Hammer" },
  { id: 15, name: "Kettlebell" },
  { id: 16, name: "Medicine Ball" },
  { id: 17, name: "Olympic barbell" },
  { id: 18, name: "Power Sled" },
  { id: 19, name: "Resistance Band" },
  { id: 20, name: "Roll" },
  { id: 21, name: "Rollball" },
  { id: 22, name: "Rope" },
  { id: 23, name: "Stability ball" },
  { id: 24, name: "Stick" },
  { id: 25, name: "Suspension" },
  { id: 26, name: "Trap bar" },
  { id: 27, name: "Vibrate Plate" },
  { id: 28, name: "Wheel roller" },
];

export const EQUIPMENT_MAP: Record<string, string> = {
  '1': 'Barbell',
  '2': 'Body weight',
  '3': 'Cable',
  '4': 'Dumbbell',
  '5': 'EZ Barbell',
  '6': 'Leverage machine',
  '7': 'Sled machine',
  '8': 'Smith machine',
  '9': 'Weighted',
  '10': 'Assisted',
  '11': 'Band',
  '12': 'Battling Rope',
  '13': 'Bosu ball',
  '14': 'Hammer',
  '15': 'Kettlebell',
  '16': 'Medicine Ball',
  '17': 'Olympic barbell',
  '18': 'Power Sled',
  '19': 'Resistance Band',
  '20': 'Roll',
  '21': 'Rollball',
  '22': 'Rope',
  '23': 'Stability ball',
  '24': 'Stick',
  '25': 'Suspension',
  '26': 'Trap bar',
  '27': 'Vibrate Plate',
  '28': 'Wheel roller',
};

export const MUSCLES = [
  { id: 1, name: "Thighs" },
  { id: 2, name: "Chest" },
  { id: 3, name: "Hips" },
  { id: 4, name: "Back" },
  { id: 5, name: "Upper Arms" },
  { id: 6, name: "Shoulders" },
  { id: 7, name: "Forearms" },
  { id: 8, name: "Calves" },
  { id: 9, name: "Neck" },
  { id: 10, name: "Cardio" },
  { id: 12, name: "Waist" },
  { id: 17, name: "Biceps" },
  { id: 18, name: "Triceps" },
  { id: 19, name: "Quadriceps" },
  { id: 20, name: "Hamstrings" },
];

export const MUSCLE_MAP: Record<string, string> = {
  '1': 'Thighs',
  '2': 'Chest',
  '3': 'Hips',
  '4': 'Back',
  '5': 'Upper Arms',
  '6': 'Shoulders',
  '7': 'Forearms',
  '8': 'Calves',
  '9': 'Neck',
  '10': 'Cardio',
  '12': 'Waist',
  '17': 'Biceps',
  '18': 'Triceps',
  '19': 'Quadriceps',
  '20': 'Hamstrings',
};

export const EXERCISES = [
  {
    id: '1',
    name: 'BARBELL BENCH PRESS',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDlel65jEH6zPP3YezdBzkaYhW9b7fXoNzKC2Lm2lrz16Ppnxj_1kuwZZrlppS5lReXX7Pspin29VTZCuvBoieszRblsLpxzn6XmE93HkRYetqBFpWx4Bv9vDS_UtsoI0ImAxsoAGpbwdb5eAS5SDw9wGR2xatOxeddN12NrXRe1chcFPsfS8GL-2NTAeLVTFkou8FUz5v-MyhdMDWPnUTJ_9Rd1BW_Dx8tFkchrixcdLbFSuohEhClyWoJLw5WqVYVAi0IJTRAdA',
    muscles: ['CHEST'],
    equipment: 'BARBELL',
    premium: false,
    difficulty: 'ADVANCED'
  },
  {
    id: '2',
    name: 'DUMBBELL FLYES',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDiMa8LqbiWJ1bhDl6BY35vCNvMsK-KoTR3U_fJQLSOPKEPVtKOcaTTQjHQroo0CxsTH-mz4lGjZl2mTpFrythac060Cdlt00IdNKrJ1Db91mW3Cfsqnki7s-xvO_E6SzvW6xF-9L6k7AeNEtQi6_gtGdhy3cvwb4CexaPie46U9zk0OqUWftfW-Ca8hzDsYnRTWUFfV5yO45xOsBCVFE6Pq0oR8gUrdSidf-eqfvjh2ZOmShzLOk40GZV3n9VGlq8RMoRIZSfigQ',
    muscles: ['CHEST'],
    equipment: 'DUMBBELL',
    premium: false
  },
  {
    id: '3',
    name: 'INCLINE MACHINE PRESS',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCWoJcDIVLvT0Az1qAnOl9znGoERBhJY2tK5mq4Zuiv55DQfhaMCaJ7PF0gdbLgy81iR4S8XDvdftu5wLA58iErUahvI4PezIKEgr7XVWAxIH4EOJzrz8DJkgJwQ60vpg3EzUCznFES0kI8_YN0kglbI8JCLJSLpf67t1mcDhyVNJhM5ebEKrQjDgtRJSmj7hVBfon_OwCErB0VcWFwiHdcfqw1U81HdTMWwvHIAnRgtDgPwY3XLvj5oDzfZjKI6_ozSAChpLHbvQ',
    muscles: ['UPPER CHEST'],
    equipment: 'MACHINE',
    premium: false
  },
  {
    id: '4',
    name: 'EXPLOSIVE PUSHUPS',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBChKvj0et_7ROzsIA1_aVUGKAsuhULwMxrQeRqPfvpjk6J-uqx6yEPurZHQ_xoSHmCLcmEVAVA3hTO1edMTDw1dsj6YPNablQGK8uFp5InAEhynqL43p4fkWLwAffKh_2YtNgFDwo7vWrH4rdnh9BZ7JnUpC-pUTlV4yFhH3s7JcD2Qa2jc0oAVZKqboXk9yKd2kOvYeucnr48258hJt7EXzZX-ku_aAqPnqFi-Df5t36QWp3Zg1GohG8JaHGJ5Fh_XBcl5Lf9hg',
    muscles: ['CHEST'],
    equipment: 'BODYWEIGHT',
    premium: false
  }
];

export const WEIGHT_HISTORY = [
  { week: 'Wk 01', weight: 85 },
  { week: 'Wk 02', weight: 92 },
  { week: 'Wk 03', weight: 88 },
  { week: 'Wk 04', weight: 105 },
  { week: 'Wk 05', weight: 100 },
  { week: 'Wk 06', weight: 112 },
  { week: 'Wk 07', weight: 115 },
  { week: 'Wk 08', weight: 125 }
];
